services:
  app:
    build:
      context: .
      dockerfile: docker/dev/app/Dockerfile
    volumes:
      - ./:/var/www/html:cached
      - ./storage:/var/www/html/storage:delegated
    environment:
      PHP_IDE_CONFIG: serverName=Docker
      XDEBUG_MODE: debug
      XDEBUG_CLIENT_HOST: host.docker.internal

  nginx:
    build:
      context: .
      dockerfile: docker/dev/nginx/Dockerfile
    volumes:
      - ./:/var/www/html:cached
      - ./docker/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

  scanner:
    image: sonarsource/sonar-scanner-cli:5.0
    working_dir: /usr/src
    volumes:
      - ./:/usr/src
    environment:
      SONAR_TOKEN: ${SONAR_TOKEN}
    command: -Dsonar.host.url=http://sonarqube:9000

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs: